### PR TITLE
WIP: Upstream Parsers

### PR DESCRIPTION
**Pull request by jialincheoh**
- we should be parsing the control file and not the package info 
- the repo should be git clone and not just browsing through the control file 
- fields that are planned with the parsers are: source_name, version, location, author_name, author_email

### CODE REVIEW

**Comment by jialincheoh** [comment]
Tasks accomplish in this commit @SantiagoTorres, @SahithiKasim, @absol27 
- [x] I removed the prior script that doesn't git clone the folder at https://salsa.debian.org/python-team/packages
- [x] Uploaded script named `clone_salsa.sh` that git clone all packages in https://salsa.debian.org/python-team/packages with personal access token after I was given permission by gitlab@salsa.debian.org
- [x] Commented the script on what it currently does 
- [x] Created a folder named `upstream_data` in the tower at the path /data/yellow/guacalytics/raw_data/upstream_data to put all the git clone data there.

**Comment by jialincheoh** [comment]
Extracted the below list of information with my latest github commit. File name titled `get_salsa_repo_info.sh`. 

```
{
    "id": 84649,
    "name": "python-trio",
    "ssh_url": "git@salsa.debian.org:python-team/packages/python-trio.git",
    "http_url": "https://salsa.debian.org/python-team/packages/python-trio.git",
    "created_at": "2023-07-02T11:46:23.705Z",
    "statistics": null,
    "star_count": 0,
    "forks_count": 0,
    "last_activity_at": "2023-07-02T11:46:23.705Z",
    "path": "python-trio",
    "default_branch_protection": null,
    "open_issues_count": null,
    "visibility": "public",
    "archived": false,
    "description": null,
    "topics": [],
    "issues_enabled": false,
    "merge_requests_enabled": true,
    "shared_with_groups": [],
    "request_access_enabled": true
  }
```

**Comment by jialincheoh** [comment]
Updated the script `clone_extract_salsa_info.sh` , previously it doesn't clone all 3311 repo, only cloned 100 repos of https://salsa.debian.org/python-team/packages

**Comment by jialincheoh** [comment]
Latest Scripts @SantiagoTorres 

scripts/ingestion/parsers/clone_repos.py 

**Functionalities**

1) If repo exists, pull newest data
2) If repo not exists, clone the repo 
3) Check directory if empty, if empty, log error on empty directory 
4) If cannot clone repo such as https://packages.debian.org/stable/389-console, log git command error 
5) If OSError, log OSError 
6) log file named `loginfo.log`.

**Comment by SahithiKasim** [comment]
@absol27 is going to implement these scripts.

**Pull request closed without merging**
